# Array Creation Functions

In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3])
print("Array a:",a)

Array a: [1 2 3]


In [3]:
b=np.arange(0,10,3)
print('Array b=',b)

Array b= [0 3 6 9]


In [4]:
d=np.zeros((2,3))
print("Array d:\n",d)

Array d:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [5]:
d=np.zeros((2,3),dtype=int)
print("Array d:\n",d)

Array d:
 [[0 0 0]
 [0 0 0]]


In [6]:
e=np.ones((2,3))
print("Array e:\n",e)

Array e:
 [[1. 1. 1.]
 [1. 1. 1.]]


In [7]:
f=np.eye(4)
print("Identity matrix f:\n",f)

Identity matrix f:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# Array manipulation Functions

In [8]:
a1=np.array([1,2,3])
reshaped=np.reshape(a1,(1,3))
print("Reshaped array:",reshaped)

Reshaped array: [[1 2 3]]


In [9]:
#reshape array
a1=np.array([1,2,3])
reshaped=a1.reshape((3,1))
print("Reshaped array:\n",reshaped)

Reshaped array:
 [[1]
 [2]
 [3]]


In [10]:
#flatten array
f1=np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])
flattened=np.ravel(f1)
print("Flattened array:\n",flattened)

Flattened array:
 [ 1  2  3  4  5  6  7  8  9 10]


In [11]:
#transpose an array
e1=np.array([[1,2],[3,4]])
transposed=np.transpose(e1)
print("Transposed array:\n",transposed)

Transposed array:
 [[1 3]
 [2 4]]


In [12]:
#stack arrays vertically
a2=np.array([1,2])
b2=np.array([3,4])
stacked=np.vstack((a2,b2))
print("Stacked array:\n",stacked)

Stacked array:
 [[1 2]
 [3 4]]


In [13]:
#stack arrays horizontally
a2=np.array([1,2])
b2=np.array([3,4])
stacked=np.hstack((a2,b2))
print("Stacked array:\n",stacked)

Stacked array:
 [1 2 3 4]


# Mathematical functions

In [14]:
#add two arrays
g=np.array([1,2,3,4])
added=np.add(g,2)
print("Added 2 to g:\n",added)

Added 2 to g:
 [3 4 5 6]


In [15]:
#square each element of an array
squared=np.power(g, 2)
print("Squared array:\n",squared)

Squared array:
 [ 1  4  9 16]


In [16]:
#square root of each element
sqrt_val=np.sqrt(g)
print("Square root of g:",sqrt_val)

Square root of g: [1.         1.41421356 1.73205081 2.        ]


In [17]:
print(a)
print(g)

[1 2 3]
[1 2 3 4]


In [18]:
a3=np.array([1,2,3])
dot_product=np.dot(a,g)
print("Dot product of a1 and a:",dot_product)

ValueError: shapes (3,) and (4,) not aligned: 3 (dim 0) != 4 (dim 0)

In [19]:
print(a)
print(a1)

[1 2 3]
[1 2 3]


In [20]:
a3=np.array([1,2,3])
dot_product=np.dot(a1,a)
print("Dot product of a1 and a:",dot_product)

Dot product of a1 and a: 14


# Statistical functions

In [21]:
s=np.array([1,2,3,4])
mean=np.mean(s)
print("Mean of s:",mean)

Mean of s: 2.5


In [ ]:
#variance of an array
var=np.var(s)
print("Variance of s:",var)

Variance of s: 1.25


In [23]:
#standard deviation of an array
std_dev=np.std(s)
print("Standard deviation of s:",std_dev)

Standard deviation of s: 1.118033988749895


In [24]:
s

array([1, 2, 3, 4])

In [25]:
#minimum value in an array
min_val=np.min(s)
print("Minimum value in s:",min_val)

Minimum value in s: 1


In [26]:
#maximum value in an array
max_val=np.max(s)
print("Maximum value in s:",max_val)

Maximum value in s: 4


# Linear algebra functions

In [27]:
#create a matrix
matrix=np.array([[1,2],[3,4]])
matrix

array([[1, 2],
       [3, 4]])

# Random sampling functions

In [28]:
#generate random values between 0 and 1
random_values=np.random.rand(3)
print("Random values between 0 and 1:",random_values)

Random values between 0 and 1: [0.60808439 0.80075873 0.49336983]


In [29]:
#set seed for reproducibility
np.random.seed(0)

#generate random values between 0 and 1
random_values=np.random.rand(3)
print("Random values between 0 and 1:",random_values)

Random values between 0 and 1: [0.5488135  0.71518937 0.60276338]


In [30]:
#generate random integers
rand_ints=np.random.randint(0,10,size=5)
print("Random integers:",rand_ints)

Random integers: [3 7 9 3 5]


In [31]:
#set seed for reproducibility
np.random.seed(0)

#generate random integers
rand_ints=np.random.randint(0,10,size=5)
print("Random integers:",rand_ints)

Random integers: [5 0 3 3 7]


# Boolean & Logical functions

In [32]:
#check all the elements are True
logical_test=np.array([True, False, True])
all_true=np.all(logical_test)
print("All elements are True:",all_true)

All elements are True: False


In [33]:
#check if any element is True
any_true=np.any(logical_test)
print("Any element is True:",any_true)

Any element is True: True


# Set operations

In [34]:
#intersection of two arrays
set_a=np.array([1,2,3,4])
set_b=np.array([3,4,5,6])
intersection=np.intersect1d(set_a,set_b)
print("Intersection of set_a and set_b:",intersection)

Intersection of set_a and set_b: [3 4]


In [35]:
#union of two arrays
union=np.union1d(set_a,set_b)
print("Union of set_a and set_b:",union)

Union of set_a and set_b: [1 2 3 4 5 6]
